### ISSUE TITLE
Some values show NULL, some show 0 (Deye-SUN-2000G3-EU | deye_4mppt)

### ISSUE THREAD

**Issue by bolausson** [catalinsanda/org.openhab.binding.solarman#11]
Hello,

again, thanks for your efforts of bringing this binding to OpenHab!

Most of the currently gathered values are shown correct for my Deye-SUN-2000G3-EU (deye_4mppt), some values though are not gathered properly (or have another issue).

Total Production - Shows NULL whereas it should show somethig around 244 kWh
![image](https://github.com/catalinsanda/org.openhab.binding.solarman/assets/10600678/39115b52-a286-43c4-a8e3-c68b441ed86f)

Daily Production - Shows NULL, but it should show somethign aroun 0.5 kWh
![image](https://github.com/catalinsanda/org.openhab.binding.solarman/assets/10600678/23a0269e-4c71-4a1a-ba76-8fd864b793a0)

Running state is NULL - at the time of writing this, it is defenitely running :)
![image](https://github.com/catalinsanda/org.openhab.binding.solarman/assets/10600678/d514e604-18bd-45f4-9be8-a1241c28e76a)
![image](https://github.com/catalinsanda/org.openhab.binding.solarman/assets/10600678/678f66a6-400d-4f9d-b37b-cf740f3b02b8)

PV3 Current - is reported as NULL (No solar pannel attached)
![image](https://github.com/catalinsanda/org.openhab.binding.solarman/assets/10600678/3c19dd6a-e7e9-4167-9981-1c6e83ffbfb8)

PV4 Current - is reported as 0 (again, no solar pannel attached). Why is this showing 0 when PV3 is showing NULL?
![image](https://github.com/catalinsanda/org.openhab.binding.solarman/assets/10600678/1d91025b-7127-49b4-84d0-a5a8803c9af0)

Let me know if you need mor info to track down those issues :-)

Example for all values:
![image](https://github.com/catalinsanda/org.openhab.binding.solarman/assets/10600678/4d86a3e6-dac2-4b9d-a6ce-a15a91d2cfb8)

**Comment by catalinsanda** [comment]
Hey, thanks for posting the issue.

I'll try to look into it over this weekend. In the meantime, if you have the time, can you post the debug logs? It will help me see what values are returned for the registers you get null or zero values.

To enable them issue a:
`log:set TRACE org.openhab.binding.solarman`
in the console.

Thanks,
Catalin

**Comment by bolausson** [comment]
Hej Catalin,

thanks for the quick response!

the NULL issue might have been caused by myself:
```
Failed to update item 'DeyeSUN2000G3EU_PV3_Current' because '0 A' could not be converted to the item unit 'V'
Failed to update item 'DeyeSUN2000G3EU_Daily_Production' because '1 kWh' could not be converted to the item unit 'W'
Failed to update item 'DeyeSUN2000G3EU_Total_Production' because '246.1 kWh' could not be converted to the item unit 'W'
```

I changed
PV3_Current
from  type Number:ElectricPotential to Number:ElectricCurrent --> Works now
Daily_Production
from type Number:Power to Number:Energy --> Should work (can't confirm yet as there is no sun)
Total_Production
from type Number:Power to Number:Energy --> Works now

I can't remember if I did this asignment initially wrong or if there is "default" which is being picked up when assigning a new item. Might as well be my fault :)

I tried to change Running_Status from type "switch" to type "string" and see if that yields anything interesting and indeed, it now returns:
`1970-01-01T01:00:00.000+0100`
This doesn't look right :)

What happens often is this:
![image](https://github.com/catalinsanda/org.openhab.binding.solarman/assets/10600678/eef9b310-8b93-4129-9c9b-ce9ae0c03e74)

I have to go back to the thing and hit "Save" and then I can go back to the channels and see all the channels - not sure though if this is OpenHAB thing or specific to your binding.

Here are some the trace logs after all the above mentioned changes:
```
2023-07-27 10:56:02.981 [DEBUG] [arman.internal.SolarmanLoggerHandler] - Fetching data from logger
2023-07-27 10:56:02.999 [DEBUG] [rnal.modbus.SolarmanLoggerConnection] - Request frame: A5170010450000733AE6F602000000000000000000000000000001030003007E35EA9B15
2023-07-27 10:56:03.329 [DEBUG] [rnal.modbus.SolarmanLoggerConnection] - Response frame: A50F01101500ED733AE6F60201616173002C200000C1CF4E640103FC3232303832313233363900000000120C070000000126060300004E2
000000401004B0000003C17071B0A3415000000000ABE07081450128E000000000000139C002C0000000000000000006400000000000100000000000100000000000100000000000A0000000000000000000000000002000100000000099D00000000000
0000000000483000004990000093800000000000200000000138800000000000000000000000002300000000000000D52000000000000000000000000000000000000000000000000000000000000000000000000011E000901220009000000000000000
000000000000000000000000000000000000000000000000099822115
2023-07-27 10:57:02.981 [DEBUG] [arman.internal.SolarmanLoggerHandler] - Fetching data from logger
2023-07-27 10:57:02.991 [DEBUG] [rnal.modbus.SolarmanLoggerConnection] - Request frame: A5170010450000733AE6F602000000000000000000000000000001030003007E35EA9B15
2023-07-27 10:57:03.324 [DEBUG] [rnal.modbus.SolarmanLoggerConnection] - Response frame: A50F01101500EF733AE6F602019D61730068200000C1CF4E640103FC3232303832313233363900000000120C070000000126060300004E2
000000401004B0000003C17071B0A3415000000000ABE07081450128E000000000000139C002C0000000000000000006400000000000100000000000100000000000100000000000A0000000000000000000000000002000100000000099D00000000000
0000000000483000004990000092400000000000200000000139200000000000000000000000001FE0000000000000D660000000000000000000000000000000000000000000000000000000000000000000000000134000801480007000000000000000
000000000000000000000000000000000000000000000000059735C15
2023-07-27 10:58:02.981 [DEBUG] [arman.internal.SolarmanLoggerHandler] - Fetching data from logger
2023-07-27 10:58:02.991 [DEBUG] [rnal.modbus.SolarmanLoggerConnection] - Request frame: A5170010450000733AE6F602000000000000000000000000000001030003007E35EA9B15
2023-07-27 10:58:03.325 [DEBUG] [rnal.modbus.SolarmanLoggerConnection] - Response frame: A50F01101500F1733AE6F60201D9617300A4200000C1CF4E640103FC3232303832313233363900000000120C070000000126060300004E2
000000401004B0000003C17071B0A3919000000000ABE07081450128E000000000000139C002C0000000000000000006400000000000100000000000100000000000100000000000A0000000000000000000000000002000100000000099D00000000000
0000000000483000004990000092400000000000200000000139200000000000000000000000001FE0000000000000D660000000000000000000000000000000000000000000000000000000000000000000000000134000801480007000000000000000
000000000000000000000000000000000000000000000000084780F15
```

Cheers,
Bjoern

**Comment by catalinsanda** [comment]
Looking at the definition:

``` 
- name: "Running Status"
        class: ""
        state_class: ""
        uom: ""
        scale: 1
        rule: 1
        registers: [0x003B]
        isstr: true
        lookup:
          - key: 0
            value: "Stand-by"
          - key: 1
            value: "Self-check"
          - key: 2
            value: "Normal"
          - key: 3
            value: "Warning"
          - key: 4
            value: "Fault"
        icon: 'mdi:home-lightning-bolt'
```
and parsing your logs, at register 0x003B you get:
```
[003B]: 0002 (2)
```
which is "Normal".

The binding doesn't map integer values to string yet using the lookup values. It's on the TODO list. 
In the meantime you can use a number instead of a string and use the Map transformation service: https://www.openhab.org/addons/transformations/map/

**Comment by bolausson** [comment]
Again, seems to be my mistake - Setting it to "number" works now!

Thanks! I'll do the mapping in Grafana :)

```
label: Running Status
type: Number
category: status
groupNames: []
groupType: None
function: null
tags:
  - Point
```

![image](https://github.com/catalinsanda/org.openhab.binding.solarman/assets/10600678/43bcc1a6-027e-4fb6-8e71-a06b3f98f6f1)

Greetings,
Bjoern

**Comment by catalinsanda** [comment]
Glad it works, closing this.
